/**
 * Trade-specific Whisper vocabulary prompts.
 * Extracted from ai.js for maintainability.
 */
const DB = require('../../../database/db');

const TRADE_WHISPER_PROMPTS = {
  electrical: 'Construction electrical work: cable tray, conduit, EMT, RGS, RMC, IMC, PVC, LFMC, raceway, pull wire, Cadweld, megger, Megger, Hipot, hi-pot, switchgear, panelboard, MCC, motor control center, transformer, junction box, J-box, NEC, NFPA, OSHA, JSA, PPE, scaffold, cable tray support, trapeze hanger, Unistrut, strut, threader, bender, knockout, LB, condulet, wire pull, fish tape, cable rack, ladder tray, trough, nipple, coupling, connector, ground rod, ground grid, busbar, breaker, disconnect, motor starter, VFD, variable frequency drive, lug, termination, splice, heat shrink, torque wrench, interlock, THHN, THWN, XHHW, MC cable, MI cable, TC cable, SOOW, ampacity, amperage, Eaton, Square D, Schneider Electric, Siemens, Allen-Bradley, ABB, Cutler-Hammer, GE, General Electric, Hubbell, Appleton, Crouse-Hinds, Cooper, Myers hub, Hoffman, medium voltage, 480 volt, 277 volt, 4160 volt, 13.8 kV, arc flash, NFPA 70E, relay, CT, current transformer, PT, potential transformer, UPS, battery charger, cathodic protection, heat trace, Raychem, Chromalox, Thermon, motor alignment, Fluke, multimeter, ammeter.',
  instrumentation: 'Construction instrumentation and controls work: transmitter, transducer, thermocouple, RTD, resistance temperature detector, control valve, positioner, I/P converter, 4-20 milliamp, HART, Foundation Fieldbus, DCS, PLC, loop check, loop diagram, loop sheet, calibration, calibrator, Beamex, Fluke, zero, span, as-found, as-left, tuning, PID, thermowell, manifold, impulse line, pressure test, orifice plate, magnetic flow meter, Coriolis, vortex, radar level, level transmitter, pressure transmitter, temperature transmitter, differential pressure, DP, instrument air, pneumatic, solenoid valve, limit switch, proximity switch, junction box, J-box, marshalling cabinet, intrinsically safe, IS barrier, zener barrier, cable tray, conduit, instrument tubing, Swagelok, compression fitting, tube bender, flare fitting, tag number, nameplate, P&ID, ISA, NEC, OSHA, JSA, PPE, Rosemount, Emerson, Yokogawa, Endress+Hauser, Endress Hauser, Fisher, Masoneilan, Foxboro, Honeywell, Siemens, ABB, Schneider, Krohne, VEGA, Magnetrol, Dwyer, Ashcroft, Wika, Omega, Daniel, Micro Motion, Anderson Greenwood, Swagelok, Parker, Hoke, Whitey, Neles, Metso, Rotork, Limitorque, ASCO, SOR, United Electric, Bettis, EIM, Flowserve, FCI, Drexelbrook, Guided Wave Radar, GWR, displacer, SIS, safety instrumented system, SIL, safety integrity level, trip, interlock.',
  pipe_fitting: 'Construction pipe fitting work: pipe spool, flange, elbow, tee, reducer, coupling, union, nipple, weld, butt weld, socket weld, threaded, pipe hanger, pipe support, spring hanger, constant support hanger, strut, Unistrut, pipe clamp, U-bolt, pipe rack, hydrostatic test, hydrotest, pneumatic test, pressure test, NDE, radiograph, RT, dye penetrant, PT, magnetic particle, MT, ultrasonic, UT, weld map, fit-up, tack weld, root pass, hot pass, fill pass, cap pass, purge, GTAW, TIG, SMAW, stick weld, FCAW, flux core, pipe schedule, wall thickness, carbon steel, stainless steel, alloy, chrome-moly, P91, P22, P11, duplex, super duplex, Inconel, Monel, gasket, spiral wound gasket, ring joint, RTJ, raised face, flat face, bolt torque, flange bolt-up, pipe bender, pipe cutter, beveling machine, orbital weld, ASME B31.3, B31.1, Section IX, WPS, PQR, welder qualification, OSHA, JSA, PPE, Victaulic, Gruvlok, Anvil, Bonney Forge, Vogt, Velan, Swagelok, Neway, Newco, Cameron, gate valve, globe valve, check valve, ball valve, butterfly valve, plug valve, steam trap, Armstrong, Spirax Sarco, condensate, expansion loop, expansion joint, olet, weldolet, sockolet, threadolet, hot tap, line stop.',
  industrial_erection: 'Construction ironwork and steel erection: structural steel, W-beam, wide flange, HSS, hollow structural section, angle iron, channel, C-channel, I-beam, column, base plate, anchor bolt, J-bolt, L-bolt, shim plate, leveling nut, grout, non-shrink grout, Hilti, Dayton, high-strength bolt, A325, A490, tension control bolt, TC bolt, DTI, direct tension indicator, snug-tight, pretensioned, slip-critical, turn-of-nut, torque wrench, impact wrench, spud wrench, drift pin, erection bolt, moment connection, shear connection, beam clamp, safety cable, topping out, plumb, plumb bob, transit, laser level, total station, crane, mobile crane, crawler crane, tower crane, derrick, boom, jib, outrigger, counterweight, load chart, rigging, sling, choker, basket hitch, vertical hitch, shackle, clevis, eye bolt, turnbuckle, spreader bar, equalizer beam, come-along, chain fall, tugger, wire rope, synthetic sling, alloy chain sling, OSHA, JSA, PPE, harness, SRL, self-retracting lifeline, lanyard, tie-off, connector, leading edge, controlled access zone, safety net, steel decking, grating, handrail, checkered plate, Nucor, AISC, AWS D1.1.',
  safety: 'Construction safety observation: JSA, JHA, job safety analysis, job hazard analysis, PPE, personal protective equipment, hard hat, safety glasses, safety goggles, face shield, gloves, leather gloves, rubber gloves, fall protection, harness, lanyard, SRL, self-retracting lifeline, anchor point, scaffold, guardrail, barricade, LOTO, lockout tagout, confined space, permit, hot work, fire watch, fire extinguisher, first aid, near miss, incident, OSHA, toolbox talk, safety stand-down, SWA, stop work authority, AHA, activity hazard analysis, BBS, behavior-based safety, GHS, SDS, safety data sheet, respiratory, SCBA, air monitor, four-gas monitor, LEL, H2S, oxygen deficient, heat stress, WBGT, cold stress, arc flash, NFPA 70E, excavation, trench, shoring, benching, sloping, competent person, signal person, rigger, spotter.',
  millwright: 'Construction millwright and mechanical work: pump, centrifugal pump, positive displacement pump, reciprocating pump, compressor, centrifugal compressor, reciprocating compressor, screw compressor, turbine, steam turbine, gas turbine, gearbox, gear reducer, fan, blower, exhauster, agitator, mixer, conveyor, belt conveyor, screw conveyor, bucket elevator, alignment, laser alignment, dial indicator, reverse dial indicator, Fixturlaser, SKF, TKSA, Hamar, soft foot, thermal growth, coupling, flexible coupling, gear coupling, disc coupling, diaphragm coupling, grid coupling, Lovejoy, jaw coupling, spacer coupling, bearing, ball bearing, roller bearing, tapered roller, spherical bearing, thrust bearing, sleeve bearing, journal bearing, Timken, FAG, NSK, SKF, bearing clearance, bearing fit, press fit, heat fit, shrink fit, interference fit, mechanical seal, John Crane, Flowserve, Burgmann, single seal, double seal, cartridge seal, packing, packing gland, lantern ring, baseplate, sole plate, grout, epoxy grout, Masterflow, Chockfast, non-shrink grout, anchor bolt, leveling screw, jacking bolt, shim, shim stock, vibration, vibration analysis, imbalance, misalignment, looseness, resonance, CSI, Emerson, proximity probe, accelerometer, API 610, API 686, API 617, impeller, wear ring, volute, casing, shaft, keyway, key, set screw, retaining ring, O-ring, gasket, oil analysis, lubrication, grease, Mobil, Shell, Chevron, oil mist, LOTO, lockout tagout, rotation check, megger, run out, TIR, total indicator reading, OSHA, JSA, PPE.',
  sparks: 'Software development team: AI, machine learning, API, frontend, backend, React, Node.js, PostgreSQL, deployment, Docker, PM2, Cloudflare, voice report, transcription, Whisper, Claude, prompt engineering, product roadmap, sprint, standup, pull request, code review, merge, branch, commit, refactor, debug, feature, bug fix, CI, CD, deployment pipeline.',
  default: 'Construction work: conduit, cable tray, pipe, valve, transmitter, instrument, wire, panel, transformer, scaffold, JSA, PPE, OSHA, safety, harness, NEC.',
};

async function getTradeWhisperPrompt(personId, dbOverride) {
  if (!personId) return TRADE_WHISPER_PROMPTS.default;
  try {
    const person = await (dbOverride || DB).people.getById(personId);
    if (!person || !person.trade) return TRADE_WHISPER_PROMPTS.default;
    const tradeKey = person.trade.toLowerCase().replace(/[\s-]+/g, '_');
    return TRADE_WHISPER_PROMPTS[tradeKey] || TRADE_WHISPER_PROMPTS.default;
  } catch (err) {
    console.error('Trade lookup for Whisper prompt failed:', err.message);
    return TRADE_WHISPER_PROMPTS.default;
  }
}

module.exports = { TRADE_WHISPER_PROMPTS, getTradeWhisperPrompt };
